"""
data/mock_data.py — Simulated Hyperzod order database.

Contains a dictionary of fake orders used by the agent's tools
to look up order information, ETAs, refund eligibility, etc.
7 orders covering all statuses and refund scenarios.
"""

ORDERS = {
    "HZ001": {
        "order_id": "HZ001",
        "customer_name": "Aarav Mehta",
        "merchant_name": "Burger Barn",
        "items": ["Classic Smash Burger", "Loaded Fries", "Iced Cola"],
        "status": "out_for_delivery",
        "driver_name": "Ravi Kumar",
        "eta_minutes": 12,
        "total_amount": 349.00,
        "refund_eligible": False,
        "refund_status": "none",
    },
    "HZ002": {
        "order_id": "HZ002",
        "customer_name": "Priya Sharma",
        "merchant_name": "Dragon Wok",
        "items": ["Kung Pao Chicken", "Veg Fried Rice", "Spring Rolls"],
        "status": "delivered",
        "driver_name": "Sunil Yadav",
        "eta_minutes": 0,
        "total_amount": 520.50,
        "refund_eligible": True,
        "refund_status": "none",
    },
    "HZ003": {
        "order_id": "HZ003",
        "customer_name": "Rohan Gupta",
        "merchant_name": "Pizza Planet",
        "items": ["Margherita Pizza (Large)", "Garlic Bread", "Pepsi 500ml"],
        "status": "preparing",
        "driver_name": "Amit Verma",
        "eta_minutes": 28,
        "total_amount": 475.00,
        "refund_eligible": False,
        "refund_status": "none",
    },
    "HZ004": {
        "order_id": "HZ004",
        "customer_name": "Sneha Iyer",
        "merchant_name": "Green Bowl",
        "items": ["Quinoa Salad", "Avocado Smoothie"],
        "status": "cancelled",
        "driver_name": "N/A",
        "eta_minutes": 0,
        "total_amount": 310.00,
        "refund_eligible": True,
        "refund_status": "processed",
    },
    "HZ005": {
        "order_id": "HZ005",
        "customer_name": "Kabir Singh",
        "merchant_name": "Tandoori Nights",
        "items": ["Butter Chicken", "Naan (2)", "Dal Makhani", "Raita"],
        "status": "placed",
        "driver_name": "Pending Assignment",
        "eta_minutes": 45,
        "total_amount": 680.00,
        "refund_eligible": True,
        "refund_status": "none",
    },
    "HZ006": {
        "order_id": "HZ006",
        "customer_name": "Ananya Desai",
        "merchant_name": "Sushi Station",
        "items": ["Salmon Nigiri (6pc)", "Miso Soup", "Edamame", "Matcha Latte"],
        "status": "out_for_delivery",
        "driver_name": "Deepak Nair",
        "eta_minutes": 8,
        "total_amount": 890.00,
        "refund_eligible": False,
        "refund_status": "none",
    },
    "HZ007": {
        "order_id": "HZ007",
        "customer_name": "Vikram Joshi",
        "merchant_name": "Chai Point",
        "items": ["Masala Chai (2)", "Butter Croissant", "Egg Puff"],
        "status": "delivered",
        "driver_name": "Arjun Patil",
        "eta_minutes": 0,
        "total_amount": 195.00,
        "refund_eligible": True,
        "refund_status": "requested",
    },
}
